# Generated by Django 4.1.3 on 2022-11-13 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=48, verbose_name='car brand')),
                ('model', models.CharField(max_length=48, verbose_name='car model')),
                ('price', models.IntegerField(verbose_name='rent price (day)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='is featured')),
                ('image', models.ImageField(upload_to='cars/', verbose_name='image')),
                ('description', models.TextField(verbose_name='description')),
                ('mileage', models.IntegerField(verbose_name='mileage')),
                ('transmission', models.CharField(max_length=12, verbose_name='transmission')),
                ('seats', models.IntegerField(verbose_name='seats adults')),
                ('luggage', models.IntegerField(verbose_name='luggage bags')),
                ('fuel', models.CharField(max_length=12, verbose_name='fuel')),
                ('conditioner', models.BooleanField(default=True, verbose_name='conditioner')),
                ('gps', models.BooleanField(default=True, verbose_name='gps')),
                ('child_seat', models.BooleanField(default=True, verbose_name='child seat')),
                ('trunk', models.BooleanField(default=True, verbose_name='trunk')),
                ('music', models.BooleanField(default=True, verbose_name='music')),
                ('seat_belt', models.BooleanField(default=True, verbose_name='seat belt')),
                ('sleeping_bed', models.BooleanField(default=True, verbose_name='slipping bed')),
                ('water', models.BooleanField(default=True, verbose_name='water')),
                ('bluetooth', models.BooleanField(default=True, verbose_name='bluetooth')),
                ('onboard_computer', models.BooleanField(default=True, verbose_name='onboard computer')),
                ('audio_input', models.BooleanField(default=True, verbose_name='audio input')),
                ('long_term_trips', models.BooleanField(default=True, verbose_name='long term trips')),
                ('car_kit', models.BooleanField(default=True, verbose_name='car kit')),
                ('remote_central_locking', models.BooleanField(default=True, verbose_name='remote central locking')),
                ('climate_control', models.BooleanField(default=True, verbose_name='climate control')),
                ('in_rent', models.BooleanField(default=False, verbose_name='in rent')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'car',
                'verbose_name_plural': 'cars',
                'db_table': 'rental_cars',
                'ordering': ('price',),
            },
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up_location', models.CharField(max_length=48, verbose_name='pick-up location')),
                ('drop_off_location', models.CharField(max_length=48, verbose_name='pick-off location')),
                ('pick_up_date', models.CharField(max_length=48, verbose_name='pick-up date')),
                ('drop_off_date', models.CharField(max_length=48, verbose_name='drop-off date')),
                ('pick_up_time', models.CharField(max_length=48, verbose_name='pick-up time')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2022, 11, 13, 18, 17, 42, 36864, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'verbose_name': 'rent',
                'verbose_name_plural': 'rents',
                'db_table': 'rent_car',
                'ordering': ('date_created',),
            },
        ),
    ]
