# Generated by Django 4.1.3 on 2022-11-07 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=48, verbose_name='title')),
                ('subtitle', models.CharField(max_length=48, verbose_name='subtitle')),
                ('image', models.ImageField(upload_to='posts/', verbose_name='image')),
                ('text', models.TextField(verbose_name='text')),
                ('is_published', models.BooleanField(default=True, verbose_name='is published')),
                ('date_published', models.DateTimeField(default=datetime.datetime(2022, 11, 7, 14, 1, 54, 430196, tzinfo=datetime.timezone.utc), verbose_name='date published')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'db_table': 'blog_posts',
                'ordering': ('date_published',),
            },
        ),
    ]
