# Generated by Django 4.1.3 on 2022-11-13 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_date_published_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('message', models.TextField(verbose_name='contact message')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2022, 11, 13, 18, 17, 42, 34672, tzinfo=datetime.timezone.utc), verbose_name='date contact')),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
                'db_table': 'contact',
                'ordering': ('date_created',),
            },
        ),
        migrations.AddField(
            model_name='post',
            name='author_about',
            field=models.TextField(default='No information', verbose_name='about author'),
        ),
        migrations.AddField(
            model_name='post',
            name='author_image',
            field=models.ImageField(null=True, upload_to='posts/', verbose_name='author image'),
        ),
        migrations.AddField(
            model_name='post',
            name='author_name',
            field=models.CharField(default='No information', max_length=96, verbose_name='author name'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 13, 18, 17, 42, 34672, tzinfo=datetime.timezone.utc), verbose_name='date comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 13, 18, 17, 42, 33383, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
