# Generated by Django 4.1.3 on 2022-11-18 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 18, 18, 50, 24, 814561, tzinfo=datetime.timezone.utc), verbose_name='date comment'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 18, 18, 50, 24, 815579, tzinfo=datetime.timezone.utc), verbose_name='date contact'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 18, 18, 50, 24, 814561, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
