# Generated by Django 4.1.3 on 2022-11-18 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_author_alter_comment_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 18, 20, 47, 42, 927409, tzinfo=datetime.timezone.utc), verbose_name='date comment'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 18, 20, 47, 42, 927409, tzinfo=datetime.timezone.utc), verbose_name='date contact'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 18, 20, 47, 42, 927409, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
